Hlt 101
techmely/hoc-lap-trinh pull request #111
Opened 2023-09-14 14:11 UTC by yusaki0998

2023-09-14 16:28 UTC, thaycacac requested changes

2023-09-14 16:28 UTC, thaycacac commented on c/01-introduction/02-cau-truc-chuong-trinh-c-co-ban/cau-truc-chuong-trinh-c-co-ban.md
>  --------------------------------
xoá dòng này @yusaki0998 nhé

2023-09-14 16:28 UTC, thaycacac commented on c/01-introduction/02-cau-truc-chuong-trinh-c-co-ban/cau-truc-chuong-trinh-c-co-ban.md
> +description: "Việc nắm vững cấu trúc cơ bản của ngôn ngữ lập trình C là một bước quan trọng để trở thành một lập trình viên thành thạo. Trong bài viết này, chúng t sẽ giới thiệu và giải thích cơ bản
`chúng t` nè

2023-09-14 16:28 UTC, thaycacac commented on c/02-basic-concepts/02-bien-va-hang-so-trong-c/bien-va-hang-so-trong-c.md
>  Kết quả:
xoá hết giúp t mấy chữ kết quả nhé, vì cái result kia nó đã viết là kết quả rồi

2023-09-14 16:28 UTC, thaycacac commented on c/02-basic-concepts/07-thu-vien-toan-trong-c/thu-vien-toan-trong-c.md
>  ### Hàm ceil
Update giùm t mấy cái này thành `Hàm ceil trong C` để lên đc top google nha

2023-09-14 16:28 UTC, thaycacac commented on c/05-functions/03-ham-de-quy-trong-c/ham-de-quy-trong-c.md
> +description: "Hàm đệ quy trong lập trình C là một công cụ mạnh mẽ cho phép giải quyết các bài toán phức tạp bằng cách sử dụng tính truy hồi. Trong bài viết này, chúng t sẽ đào sâu vào khái niệm này,
Chúng t này

2023-09-14 16:28 UTC, thaycacac commented on c/06-arrays/04-bai-tap-mang-trong-c/bai-tap-mang-trong-c.md
>  --------------------------------
Xoá khúc này đi nhé @yusaki0998

2023-09-14 16:28 UTC, thaycacac commented on c/07-pointers/02-moi-quan-he-mang-va-con-tro/moi-quan-he-mang-va-con-tro.md
> +Cì kích thước của `int` là `4 byte` nên địa chỉ của hai phần tử mảng liên tiếp cũng chênh nhau `4 byte`.
Sai chính tả này @yusaki0998

2023-09-14 16:29 UTC, thaycacac commented
@yusaki0998 cơ bản thì format cũng oke rồi đó Trung nhưng phần content khoá này rất sơ sài, nên t muốn ô tham khảo mấy khoá ở ngoài mình structure lại và viết nội dung đầy đủ nhé ô

2023-09-16 08:57 UTC, yusaki0998 commented
@thaycacac phần cập nhật nội dung khóa học t đang tham khảo rồi, trước hết sẽ đẩy phần chỉnh sửa của khóa hiện tại của mình cho đúng các đầu mục refactor trước đã.

2023-09-16 08:59 UTC, harrytran998 commented
> @yusaki0998 cơ bản thì format cũng oke rồi đó Trung nhưng phần content khoá này rất sơ sài, nên t muốn ô tham khảo mấy khoá ở ngoài mình structure lại và viết nội dung đầy đủ nhé ô

T đồng ý nên cải thiện thêm khoá này. Nhưng nếu là ticket cải thiện - nên define rõ ràng ra và tách từng ticket một để mn làm dần nhé.

2023-09-16 08:59 UTC, harrytran998 approved these changes
![LGTM](https://github.com/techmely/hoc-lap-trinh/assets/24296018/40d1fee5-e83a-46d3-9337-1b70c078c97a)

2023-09-16 14:11 UTC, thaycacac approved these changes

2023-09-16 14:11 UTC, merged